<h1><font color="#113D68" size=6>Deep Learning con Python y Keras</font></h1>

<h1><font color="#113D68" size=5>Multilayer Perceptron</font></h1>

<h1><font color="#113D68" size=4>Desarrollar una red neuronal</font></h1>

<a id="section1"></a>
# <font color="#004D7F" size=6>1. Conjunto de datos</font>

En este tutorial vamos a utilizar el conjunto de datos Pima Indians Diabetes. Describe los datos de los registros médicos de los pacientes y si tuvieron una aparición de diabetes dentro de los cinco años. Es un problema de clasificación binaria (aparición de diabetes como 1 o 0 si no aparece). Las variables de entrada que describen a cada paciente son numéricas y tienen escalas variables.

Dado que todos los atributos son numéricos, es fácil de usar directamente con redes neuronales que esperan entradas y valores de salida numéricos.

<div class="alert alert-block alert-info">
    
<i class="fa fa-info-circle" aria-hidden="true"></i>
Puede descargar el Dataset desde [Kaggle](https://www.kaggle.com/uciml/pima-indians-diabetes-database)

La precisión de la línea de base si se hacen todas las predicciones ya que no aparece la diabetes es del 65,1%. Los mejores resultados en el conjunto de datos están en el rango de 77,7% de precisión utilizando una validación cruzada de 10 veces.

<a id="section2"></a>
# <font color="#004D7F" size=6>2. Cargar datos</font>

VAmos a cargar el archivo directamente usando la función `loadtxt()` de NumPy y establecer dividir las características y target.

In [1]:
import numpy as np

dataset=np.loadtxt("pima-indians-diabetes.csv",delimiter=",")
dataset

array([[  6., 148.,  72., ..., 627.,  50.,   1.],
       [  1.,  85.,  66., ..., 351.,  31.,   0.],
       [  8., 183.,  64., ..., 672.,  32.,   1.],
       ...,
       [  5., 121.,  72., ..., 245.,  30.,   0.],
       [  1., 126.,  60., ..., 349.,  47.,   1.],
       [  1.,  93.,  70., ..., 315.,  23.,   0.]])

In [4]:
x=dataset[:,0:8]
y=dataset[:,8]

In [5]:
x

array([[  6. , 148. ,  72. , ...,  33.6, 627. ,  50. ],
       [  1. ,  85. ,  66. , ...,  26.6, 351. ,  31. ],
       [  8. , 183. ,  64. , ...,  23.3, 672. ,  32. ],
       ...,
       [  5. , 121. ,  72. , ...,  26.2, 245. ,  30. ],
       [  1. , 126. ,  60. , ...,  30.1, 349. ,  47. ],
       [  1. ,  93. ,  70. , ...,  30.4, 315. ,  23. ]])

In [6]:
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [7]:
x.shape

(768, 8)

In [8]:
y.shape

(768,)

<a id="section3"></a>
# <font color="#004D7F" size=6>3. Definir modelo</font>

Los modelos en Keras se definen como una secuencia de capas. Creamos un modelo **Secuencial** y agregamos capas de una en una hasta que estemos satisfechos con nuestra topología de red. 

Lo primero que debe hacer bien es asegurarse de que la capa de entrada tenga el número correcto de entradas. Esto se puede especificar al crear la primera capa con el argumento `input_dim` y establecerlo en 8. 

Pregunta, ¿Cómo sabemos la cantidad de capas que debemos usar y sus tipos? 


En sí el procedimiento a utilizar será:
1. Las capas completamente conectadas se definen mediante la clase `Dense`. Se puede especificar:
    * El número de neuronas en la capa como primer argumento y 
    * Especificar la función de activación usando el parámetro `activation`.
2. Usaremos la función de activación ReLu en las dos primeras capas y la función de activación Sigmoidea en la capa de salida. 
3. Usamos una función de activación sigmoidea en la capa de salida para garantizar que la salida de nuestra red esté entre 0 y 1. 

In [9]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [30]:
#modelo de la red neuronal, una capa va tras la otra, secuencial
model=Sequential()
#primera capa oculta, la capa de entrada no se define
#se debe indicar el numero de neuronas de la capa oculta
#se debe indicar el numero de neuronas de entrada 8 
#(input_dim) en este caso
#se debe indicar la funcion de activacion
model.add(Dense(12,input_dim=8,activation="relu"))
#se debe indicar el numero de neuronas
#se debe indicar la funcion de activacion
model.add(Dense(8,activation="relu"))
#se dene indicar el numero de neuronas, como es de salida
#y el problema es de clasificacion para dos categorias
#entonces se utiliza una neurona de salida
model.add(Dense(1,activation="sigmoid"))

#se usa la funcion relu de activacion para las capas ocultas
#se usa la funcion sigmoid para clasificacion y en la capa de
#salida

<a id="section4"></a>
# <font color="#004D7F" size=6>4. Compilar modelo</font>

Ahora que el modelo está definido, podemos compilarlo. 

Al compilar, debemos especificar algunas propiedades adicionales requeridas al entrenar la red. 

Debemos especificar:
1. La función de pérdida que se utilizará para evaluar un conjunto de ponderaciones, 
2. El optimizador utilizado para buscar entre diferentes ponderaciones para la red y
3. Cualquier métrica opcional que nos gustaría recopilar e informar durante el entrenamiento. 
    * En este caso usaremos la **pérdida logarítmica**, que para un problema de clasificación binaria se define como `binary_crossentropy`. 
4. También usaremos el algoritmo de Gradiente Descendiente `adam` 
5. Finalmente, debido a que es un problema de clasificación nuestra métrica será el Accuracy.

<div class="alert alert-block alert-info">
    
<i class="fa fa-info-circle" aria-hidden="true"></i>
Obtenga más información sobre el algoritmo de optimización de Adam en el artículo [_Adam: A Method for Stochastic Optimization_](https://arxiv.org/abs/1412.6980)

In [11]:
#compilar modelo
#para compilar se debe pasar la funcion de perdida
#(loss) en este caso se usa binary_crossentropy que es
#usada para problemas de clasificacion
#se debe pasar el optimizador (optimizer) normalmente se 
#utiliza adam
#y por ultimo se pasa las metricas para evaluar el modelo
#estas se deben pasar como una lista en este caso se utiliza
#accurracy
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

<a id="section5"></a>
# <font color="#004D7F" size=6>5. Ajustar modelo</font>

Hemos definido nuestro modelo y lo hemos compilado listo para un cálculo eficiente. Ahora es el momento de ejecutar el modelo en algunos datos llamando a la función `fit()`.
* El proceso de entrenamiento se ejecutará para un número fijo de iteraciones usando el argumento `epochs`. 
* También podemos establecer el número de instancias que se evalúan antes de que se realice una actualización de peso en la red, denominada tamaño de batch, y se establece mediante el argumento `batch_size`. 

In [12]:
#se ajusta el modelo
#se deben pasar las variables de entrada primero x en este caso
#luego se pasan las salidas deseadas y en este caso
#se pasa el numero de epocas (epochs) y numero de lotes (batch_size)

model.fit(x,y,epochs=200,batch_size=16)

Epoch 1/200
48/48 [==============================] - 2s 4ms/step - loss: 17.2965 - accuracy: 0.6107
Epoch 2/200
48/48 [==============================] - 0s 5ms/step - loss: 6.4032 - accuracy: 0.6198
Epoch 3/200
48/48 [==============================] - 0s 5ms/step - loss: 3.8645 - accuracy: 0.6211
Epoch 4/200
48/48 [==============================] - 0s 5ms/step - loss: 2.4511 - accuracy: 0.6367
Epoch 5/200
48/48 [==============================] - 0s 5ms/step - loss: 1.9846 - accuracy: 0.6354
Epoch 6/200
48/48 [==============================] - 0s 4ms/step - loss: 1.6198 - accuracy: 0.6263
Epoch 7/200
48/48 [==============================] - 0s 5ms/step - loss: 1.5735 - accuracy: 0.6224
Epoch 8/200
48/48 [==============================] - 0s 4ms/step - loss: 1.4198 - accuracy: 0.6133
Epoch 9/200
48/48 [==============================] - 0s 6ms/step - loss: 1.3397 - accuracy: 0.6146
Epoch 10/200
48/48 [==============================] - 0s 6ms/step - loss: 1.2068 - accuracy: 0.6003
Epoch 11

48/48 [==============================] - 0s 4ms/step - loss: 0.5708 - accuracy: 0.7148
Epoch 84/200
48/48 [==============================] - 0s 4ms/step - loss: 0.6685 - accuracy: 0.6836
Epoch 85/200
48/48 [==============================] - 0s 4ms/step - loss: 0.5955 - accuracy: 0.7044
Epoch 86/200
48/48 [==============================] - 0s 4ms/step - loss: 0.6087 - accuracy: 0.6875
Epoch 87/200
48/48 [==============================] - 0s 3ms/step - loss: 0.6055 - accuracy: 0.6927
Epoch 88/200
48/48 [==============================] - 0s 3ms/step - loss: 0.5782 - accuracy: 0.7031
Epoch 89/200
48/48 [==============================] - 0s 3ms/step - loss: 0.6286 - accuracy: 0.7083
Epoch 90/200
48/48 [==============================] - 0s 4ms/step - loss: 0.6574 - accuracy: 0.6836
Epoch 91/200
48/48 [==============================] - 0s 4ms/step - loss: 0.6250 - accuracy: 0.7044
Epoch 92/200
48/48 [==============================] - 0s 4ms/step - loss: 0.6109 - accuracy: 0.7227
Epoch 93/200


<a id="section6"></a>
# <font color="#004D7F" size=6>6. Evaluar modelo</font>

Podemos evaluar tu modelo en tu conjunto de datos de entrenamiento usando la función de `evaluation()` y pasar la misma entrada y salida que usaste para entrenar el modelo.

In [13]:
#evaluar el modelo

_,accuracy=model.evaluate(x,y)
print("acuracy: %.2f"%(accuracy*100))

24/24 [==============================] - 1s 4ms/step - loss: 0.5051 - accuracy: 0.7526
acuracy: 75.26


<a id="section7"></a>
# <font color="#004D7F" size=6>7. Hacer predicciones</font>

Podemos llamar a la función `predict_classes()` para predecir clases directamente, por ejemplo:

In [15]:
#hacer prediccion
prediccion=model.predict(x)

24/24 [==============================] - 0s 2ms/step


In [29]:
for i in range(100):
    print("serie de x: %s --> %d esperado: %d" %(x[i], list(map(lambda x: 1 if x>0.5 else 0,prediccion))[i],y[i]))

serie de x: [  6.  148.   72.   35.    0.   33.6 627.   50. ] --> 1 esperado: 1
serie de x: [  1.   85.   66.   29.    0.   26.6 351.   31. ] --> 0 esperado: 0
serie de x: [  8.  183.   64.    0.    0.   23.3 672.   32. ] --> 1 esperado: 1
serie de x: [  1.   89.   66.   23.   94.   28.1 167.   21. ] --> 0 esperado: 0
serie de x: [   0.   137.    40.    35.   168.    43.1 2288.    33. ] --> 1 esperado: 1
serie de x: [  5.  116.   74.    0.    0.   25.6 201.   30. ] --> 0 esperado: 0
serie de x: [  3.  78.  50.  32.  88.  31. 248.  26.] --> 0 esperado: 1
serie de x: [ 10.  115.    0.    0.    0.   35.3 134.   29. ] --> 1 esperado: 0
serie de x: [  2.  197.   70.   45.  543.   30.5 158.   53. ] --> 1 esperado: 1
serie de x: [  8. 125.  96.   0.   0.   0. 232.  54.] --> 0 esperado: 1
serie de x: [  4.  110.   92.    0.    0.   37.6 191.   30. ] --> 0 esperado: 0
serie de x: [ 10. 168.  74.   0.   0.  38. 537.  34.] --> 1 esperado: 1
serie de x: [  10.   139.    80.     0.     0.    27.1 1

Ejecutar el ejemplo no muestra la barra de progreso como antes, ya que hemos establecido el argumento `verbose` en 0. 